name: tide_mcp
description: A cross-platform tide, moon phase, and fishing/hunting prediction app.
version: 1.2.0
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  fl_chart: ^0.71.0
  geolocator: ^9.0.2
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
